const data = [
  {
    id: 1,
    user: 1,
    date: "20/03/2024",
    description: "pede. Nunc sed orci",
    type: "income",
    category: 4,
    amount: 865,
  },
  {
    id: 2,
    user: 1,
    date: "25/07/2023",
    description: "ipsum. Curabitur consequat, lectus",
    type: "income",
    category: 1,
    amount: 2271,
  },
  {
    id: 3,
    user: 2,
    date: "06/01/2024",
    description: "in faucibus orci luctus",
    type: "income",
    category: 7,
    amount: 734,
  },
  {
    id: 4,
    user: 2,
    date: "02/11/2022",
    description: "quis urna. Nunc quis",
    type: "income",
    category: 6,
    amount: 2458,
  },
  {
    id: 5,
    user: 1,
    date: "13/11/2022",
    description: "tristique senectus et netus",
    type: "expense",
    category: 4,
    amount: 556,
  },
  {
    id: 6,
    user: 1,
    date: "13/06/2024",
    description: "diam luctus lobortis. Class",
    type: "income",
    category: 9,
    amount: 1202,
  },
  {
    id: 7,
    user: 1,
    date: "16/01/2023",
    description: "accumsan neque et nunc.",
    type: "income",
    category: 1,
    amount: 1344,
  },
  {
    id: 8,
    user: 1,
    date: "20/06/2024",
    description: "id enim. Curabitur massa.",
    type: "income",
    category: 9,
    amount: 1943,
  },
  {
    id: 9,
    user: 1,
    date: "07/12/2023",
    description: "imperdiet dictum magna. Ut",
    type: "expense",
    category: 4,
    amount: 2458,
  },
  {
    id: 10,
    user: 1,
    date: "30/03/2024",
    description: "libero. Morbi accumsan laoreet",
    type: "income",
    category: 4,
    amount: 636,
  },
];

export default data;
